services:
  website-archive:
    build: .
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - 'traefik.docker.network=traefik'

networks:
  traefik:
    name: traefik
    external: true
