version: "3.8"
services:
  website-archive:
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.frontend.rule=Host:website-archive.justinpaulhammond.com,www.website-archive.justinpaulhammond.com
