<!DOCTYPE html>
<html lang="en">
	<head>
		<?php include 'header.php';?>
		<title>Prime Business Development</title>
		<style type="text/css">
		.pa-banner {
	    background-image: url("assets/pics/Prime-Website-Design-Crisp-3.jpg");
	    border-bottom: solid 5px #89150a;
	}
		.bg-infographic {
			/*
		  background-image: linear-gradient(141deg, #fff, #2d2a4d, #000000);
		  background-image: -webkit-linear-gradient(180deg, #89150a, #d21e16, #89150a);
		  background-image: -o-linear-gradient(141deg, #89150a, #2d2a4d, #000000);
		  */
      background-image: url("assets/pics/originals/infographic-back.jpg");
	}


  /* https://stackoverflow.com/questions/23976498/fading-bootstrap-navbar-on-scrolldown-while-changing-text-color */
  /* https://www.youtube.com/watch?v=6VZNH1gorws */

.navbar {
    background-color: initial;
}
.nav-fade {
    color: #fff !important;
    transition: background-color 0.5s ease 0s;
}
.nav-fade.opaque {
    /*background-color: rgba(255,255,255,0);*/
    color:#89150a !important;
    background-color: #fff;
    transition: background-color 0.5s ease 0s;
    opacity: 0.9;
}
.nav-fade a {
    color: #fff !important;
}

.nav-fade .dropdown-menu a {
    color: #000 !important;
}

.nav-fade a.opaque {
    color: #89150a !important;
}

</style>
	</head>
<body data-offset="110">

<?php include 'nav.php';?>

<div class="pa-banner pa-banner-darken">
	<div class="pa-banner-text" style="text-shadow: 0 0 20px black;">
    <div style="border-left: solid 5px #89150a;position: fixed;right: 0;padding:3vmin">
  		<h1 class="pa-banner-heading" style="font-size:7vmin;text-align: right">E-COMMERCE INNOVATION</h1>
      <h1 class="pa-banner-sub-heading" style="font-size:4vmin;text-align: right">Professional E-Commerce Services</h1>
    </div>
	</div>
</div>

<!--
<div id="pa-slanted-section" style="border-color: transparent #282e32 transparent transparent;"></div>
-->
<div style="border-bottom: solid 5px #89150a;color:#282e32;">
	<div class="container">
	<br>
		<div class="pa-slideanim"><p class="index-text text-center"><strong>Your E-Commerce business navigators; providing around-the-clock innovation. We are an all-inclusive, E-commerce management agency that allows you to focus on running your business.</strong></p></div>
	<br>
		<div class="pa-slideanim"><img src="assets/pics/logo_circle_red.png" style="width:30vmin;border-radius: 1em;" title="Prime Business Development" alt="Prime Business Development"></div>
	<br>
	</div>
</div>





<div class="pa-banner bg-infographic" style="color:#fff;">
	<div class="container">

<br><br>
<h1 style="color:#fff;font-size: 7vmin">Our Method</h1>
<div style="height: 1px;background-color: #fff;"></div>
<br>
<img src="assets/pics/ClickToExplore.png">


<div class="row text-center">

<div class="col">

<a href="#" data-toggle="modal" data-target="#market-research" class="transparent-hover" style="color: #fff;">

<p style="color:#fff;font-size: 4vmin">Step 1</p>
<i class="fa fa-flask" aria-hidden="true" style="font-size: 9vmin"></i>
<h2 style="color:#fff;font-size: 4vmin">Market<br>Research</h2>
</a>

</div>

<div class="col">

<a href="#" data-toggle="modal" data-target="#E-Commerce" class="transparent-hover" style="color: #fff;">

<p style="color:#fff;font-size: 4vmin">Step 2</p>
<i class="fa fa-shopping-cart" aria-hidden="true" style="font-size: 9vmin"></i>
<h2 style="color:#fff;font-size: 4vmin">E-Commerce Platform</h2>
</a>

</div>

<div class="col">

<a href="#" data-toggle="modal" data-target="#make-money" class="transparent-hover" style="color: #fff;">

<p style="color:#fff;font-size: 4vmin">Step 3</p>
<i class="fa fa-usd" aria-hidden="true" style="font-size: 9vmin"></i>
<h2 style="color:#fff;font-size: 4vmin">Make<br>Money</h2>
</a>

</div>
</div>

<br><br>

<div class="text-center">

<a href="#cards">
<i class="fa fa-chevron-down" aria-hidden="true" style="font-size: 9vmin;padding-top: 4%;color: #fff;"></i>
</a>


</div>



</div>
</div>


<!--
<div class="container-fluid">
<br><br>
<div class="pa-pa-slideanim"><h3 style="color:white;font-size:34px;text-align:center;">What We Do</h3></div>
<p class="index-text pa-slideanim" style="color: white;text-align: center;margin:0px !important;">Select an icon to learn more:</p>
<br><br>
</div>
-->



<!-- Image Map Generated by http://www.image-map.net/ -->
<!--
<img src="assets/pics/infographic-final.jpg" class="pa-slideanim" style="max-width:100%;margin:0px;background-attachment: fixed;" usemap="#infographic-mapped">

<map name="infographic-mapped" id="infographic-mapped">
    <area target="" alt="Outside Traffic" title="Outside Traffic" href="services.php" coords="1190,362,929,232" shape="rect">
    <area target="" alt="Reviews" title="Reviews" href="services.php" coords="399,441,641,541" shape="rect">
    <area target="" alt="PPC/Keywords" title="PPC/Keywords" href="services.php" coords="216,721,560,895" shape="rect">
    <area target="" alt="Listing Optimization" title="Listing Optimization" href="services.php" coords="732,922,1055,1071" shape="rect">
    <area target="" alt="International Marketplace" title="International Marketplace" href="services.php" coords="1287,659,1629,775" shape="rect">
    <area target="" alt="Sourcing" title="Sourcing" href="services.php" coords="1335,352,1486,497" shape="rect">
    <area target="" alt="Market Research" title="Market Research" href="services.php" coords="160,79,419,336" shape="rect">
    <area target="" alt="E-Commerce" title="E-Commerce" href="services.php" coords="788,472,1130,810" shape="rect">
    <area target="" alt="Money" title="Money" href="services.php" coords="1505,951,1745,1193" shape="rect">
</map>
-->




<!--
<img src="assets/pics/infographic-final.jpg" class="pa-slideanim" style="max-width:100%;margin:0px;background-attachment: fixed;" usemap="#infographic-mapped">
<map name="infographic-mapped" id="infographic-mapped">
	<area shape="rect" alt="" title="1" coords="569,587,924,751" href="#" target="" data-toggle="modal" data-target="#listing" />
	<area shape="rect" alt="" title="2" coords="328,914,848,1176" href="services.php" target="" />
	<area shape="rect" alt="" title="3" coords="961,1182,1421,1390" href="services.php" target="" />
	<area shape="rect" alt="" title="4" coords="1645,852,2141,1029" href="services.php" target="" />
	<area shape="rect" alt="" title="55" coords="1716,476,1953,689" href="services.php" target="" />
	<area shape="rect" alt="" title="6" coords="1204,337,1596,529" href="services.php" target="" />
	<!-- Created by Online Image Map Editor (http://www.maschek.hu/imagemap/index) --
</map>
-->









<div class="container-fluid" id="cards">


<br><br>
<p style="text-align: center;font-size: 30px;">Let's break it down:</p>

<br>

<div class="container-fluid">



<div class="row">

<div class="col-md-4 transparent-hover pa-slideanim">
<a href="#" data-toggle="modal" data-target="#listing-optimization">

<div class="pa-card bg-gradient-red">
		<br>
		<i class="fa fa-list fa-4x" aria-hidden="true"></i>
		<br>
		<h2 style="color:#fff">Listing<br>Optimization<br></h2>
	</div>
</a>
</div>


<div class="col-md-4 transparent-hover pa-slideanim">
<a href="#" data-toggle="modal" data-target="#keywords">

<div class="pa-card bg-gradient-red">
		<br>
		<i class="fa fa-tags fa-4x" aria-hidden="true"></i>
		<h2 style="color:#fff">PPC/Keywords<br><br></h2>
	</div>
</a>
</div>





<div class="col-md-4 transparent-hover pa-slideanim">
<a href="#" data-toggle="modal" data-target="#reviews">

<div class="pa-card bg-gradient-red">
		<br>
		<i class="fa fa-star fa-4x" aria-hidden="true"></i>
		<h2 style="color:#fff">Reviews<br><br></h2>
	</div>
</a>
</div>

</div>





<!------------------>


<div class="row">


<div class="col-md-4 transparent-hover pa-slideanim">
<a href="#" data-toggle="modal" data-target="#outside-traffic">

<div class="pa-card bg-gradient-red">
		<br>
		<i class="fa fa-plane fa-4x" aria-hidden="true"></i>
		<h2 style="color:#fff">Outside<br>Traffic</h2>
	</div>
</a>
</div>




<div class="col-md-4 transparent-hover pa-slideanim">
<a href="#" data-toggle="modal" data-target="#sourcing">

<div class="pa-card bg-gradient-red">
		<br>
		<i class="fa fa-industry fa-4x" aria-hidden="true"></i>
		<h2 style="color:#fff">Sourcing<br><br></h2>
	</div>
</a>
</div>


<div class="col-md-4 transparent-hover pa-slideanim">
<a href="#" data-toggle="modal" data-target="#international-marketplace">

<div class="pa-card bg-gradient-red">
		<br>
		<i class="fa fa-globe fa-4x" aria-hidden="true"></i>
		<h2 style="color:#fff">International<br>Marketplace</h2>
	</div>
</a>
</div>

</div>


<br>
<hr>
<br>





	<div class="col-sm-12 columns transparent-hover">
	<a href="contact-us.php">

		<i class="fa fa-paper-plane fa-4x" aria-hidden="true"></i>
		<h3>Contact Us</h3>
	</div>
</a>

<br><br>

	</div>
</div>

<?php include 'footer.php';?>

<!-- used for infographic mapping -->
<!-- https://github.com/stowball/jQuery-rwdImageMaps -->
<script src="assets/js/scale-mapped-images.js"></script>
<script>
$(document).ready(function(e) {
    $('img[usemap]').rwdImageMaps();
});
</script>
<!-- end -->






<!--********-->
<!-- Modals -->
<div class="modal fade" id="market-research" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Market Research</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>PBD has created a world class system for gathering market research so that our clients can maximize their E-Commerce experience. New clients will get access to research in order to estimate monthly sales, increase the number of client reviews and the quality of ratings, see leading trends in product industries, determine correct selling prices, improve listing quality and create appropriate goals and sales time frames.</p>
      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="E-Commerce" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">E-Commerce</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>With over 300 million users, E-Commerce is one of the largest markets in the world for building product businesses. E-Commerce allows sellers the benefits of owning a product business without the hassle of shipping products or storing inventory in a warehouse. E-Commerce sellers can also expand at a relatively low cost and scale quickly all over the world. </p>
      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="make-money" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Make Money</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>All of these services lead to increased product sales and money in your pocket.</p>
      </div>
    </div>
  </div>
</div>



<!---->



<div class="modal fade" id="listing-optimization" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Listing Optimization</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	<p><b>Content:</b> We ensure that you have keyword-friendly titles, searchable bullet points, and detailed descriptions. 

<br><br><b>Media:</b> Pictures and videos are proven to improve your conversion rates. Our in-house experts can piece together your media to match the needs of the market and E-Commerce’s regulations.</p>      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="keywords" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">PPC/Keywords</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><b>Pay-per-click ads:</b> These campaigns are crucial to stimulate and maintain a lasting sales rank. Our experienced team will manage and monitor these complex campaigns to make sure you get the most out of your money. 
<br><br><b>Keyword Research:</b> Our team conducts market research to determine which keywords will drive the most traffic to your products. These keywords will be implemented into all PPC campaigns and into product content.</p>
      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="reviews" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Reviews</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Our E-Commerce specialists will work with you to increase your positive product reviews using proven strategies. Reviews play a monumental role in increasing sales for each product.</p>
      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="outside-traffic" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Outside Traffic</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>We teach our clients how to utilize social media and other platforms to drive traffic to your E-Commerce store.</p>
      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="sourcing" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Sourcing</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Our international sourcing team is available to find and inspect factories to confirm their quality and authenticity. These native negotiators will deliver an unbeatable price with less risk for your business.</p>
      </div>
    </div>
  </div>
</div>

<!---->

<div class="modal fade" id="international-marketplace" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">International Marketplace</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" style="color:#fff;">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>E-Commerce has platforms in Japan, Mexico, Canada, The UK, Germany, France and lots more coming soon. Only being in the USA market limits your businesses potential. We help our clients reach beyond to take advantage of E-Commerce’s vast market place and the several hundred million customers world-wide.</p>
      </div>
    </div>
  </div>
</div>


<!-- Modals End -->


















</body>
</html>