name: build

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Traefik
        run: docker network create traefik
      - name: Setup Docker container
        run: |
          docker compose up -d
          docker ps | grep -q website-archive-website-archive-1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run CSS lint
        run: npm run lint-css
      - name: Run HTML lint
        run: npm run lint-html
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: ["docker", "lint"]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Harvey
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: "json-extended"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "deployment_type": "deploy", "prod_compose": true, "healthcheck": ["website-archive-website-archive-1", "website-archive-website-archive-2"] }'
